updated the readme, moved some variables to the env example file, and…
Universal-Connect-Project/ucw-example pull request #7
Opened 2024-03-21 17:14 UTC by WesRisenmay

… made the config file more clear about where values are coming from

2024-03-21 17:26 UTC, emilysallstrom requested changes

2024-03-21 17:26 UTC, emilysallstrom commented on .env.example
> +Env="pre" #mocked
Can we add the possible values that are allowed here, and expand on what "mocked" means? (I say this not knowing what mocked means, just knowing we always have used the pre environment)

2024-03-21 17:26 UTC, emilysallstrom commented on .env.example
> +UcpClientId="" #client id from the ucw app
Can we add the URL for obtaining these ids/keys, as well as how each key corresponds with the labels on that page? It's a little confusing that ClientId corresponds with `user_id`, and ClientSecret is `access_key` (I think)

2024-03-21 17:26 UTC, emilysallstrom commented on .env.example
>  # Add other credentials as needed...
Can we remove this and add stubs for the other credentials? I think there's MX Prod, Finicity, and Akoya

2024-03-21 17:26 UTC, emilysallstrom commented on README.md
> +2. Fill in the aggregator credentials in `./.env` file (e.g., if you want to see `mx bank` working in the widget, `MxClientId` and `MxApiSecret` must be provided).
Much easier to understand 👍

2024-03-25 13:17 UTC, WesRisenmay commented on .env.example
>  # Add other credentials as needed...
I'm hesitant to add those stubs without knowing where to obtain the values for them

2024-03-25 13:30 UTC, WesRisenmay commented on .env.example
> +Env="pre" #mocked
Judging by the response from Jishun it doesn't seem like we know all the possible values that can be use. The only information that seems relevant about what the environment does is the mocked environment. I added a comment for that

2024-03-25 13:30 UTC, WesRisenmay commented on .env.example
> +UcpClientId="" #client id from the ucw app
Added

2024-03-25 16:20 UTC, emilysallstrom approved these changes

2024-03-25 16:30 UTC, merged